on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: build-normal
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdiag-amd64
          path: |
            target/release/rdiag
          if-no-files-found: error
          retention-days: 1
      - id: build-musl
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdiag-musl
          path: |
            target/release/rdiag
          if-no-files-found: error
          retention-days: 1

  build_windows:
    name: Windows build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-pc-windows-msvc
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdiag-windows
          path: |
            target/release/rdiag
          if-no-files-found: error
          retention-days: 1